[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev:full"
  port = 8888
  targetPort = 3001
  publish = "dist"
  autoLaunch = true
